############################################################################################
# Configuration for UMK Project Management Postgraduate sutdy                              #
#                                            website built with Hugo and a custom theme.   #
# Developed and maintained by Maciej Koszykowski.                                          #
# Enable or disable sections using the 'enable' parameter as needed in YAML files          #
############################################################################################

title = "Project Management UMK | Studia pod patronatem PMI PC"
theme = "navigator-hugo"
languageCode = "pl"

# google analytics tracking id
# googleAnalytics = "DIFFRENT" # NOT USED HARDCODED IN THEME ###

baseURL = "https://projectmanagement.umk.pl/" 
homeURL = "https://projectmanagement.umk.pl/"  # Allows easy navigation back to the current edition from previous ones

################
#  favicon.ico #
################
# search for ./images/favicon.ico
# just replace file
# implemented in head.html parcial in the theme 


###########################################################
## Page params which normally does not need to be changed #
###########################################################

enableRobotsTXT = true       # This generates robots.txt by Hugo. This file tells search engines how to crawl and index your site.
enableGitInfo = false        # in Hugo enables inclusion of Git commit metadata (like last modified date) for your content files during site generation.
pygmentsCodeFences = true    # Might be useful so on. This enables syntax highlighting for code blocks fenced with triple backticks (```) using the Pygments highlighter in Hugo.

#In Hugo, the [markup] section configures how Markdown is processed.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # allows HTML tags and raw HTML inside Markdown files to be rendered as-is rather than escaped or stripped out.


###########################################################
## Other Site Params which are not Hugo built-in          #
###########################################################

[params]

# paga meta data
author = "UMK"
description =  "Autorski program Uniwersytetu Mikołaja Kopernika studiów podyplomowych &#8222;Project Management&#8221;, pod patronatem Project Management Institute Poland Chapter."

#### LOG files in one place 
logo = "images/logo-UMK-Project-Management-navbar.png"
logo_footer = "images/logo_WNEiZ_UMK_50.png"

# footer settings 
footerServiceTitle = "images/logo_WNEiZ_UMK_50.png"
footerQuicklinkTitle = "Mapa Strony"
footerAboutTitle = "Organizator"
PMI_PC="WNEiZ UMK w Toruniu"
PMI_PC_pl="ul. Gagarina 13a"
PMI_PC_address_ul="87-100 Toruń"
PMI_PC_address_code=" "
PMI_PC_NIP= "   "

# cookies
[params.cookies]
enable = true
expire_days = 15

###################
# Contact Section #
###################
# too static to be yaml ?
[params.contact]
enable = true
topTitle = "Project Management UMK"
title = "Kontakt"
subtitle = " "
address = "Wydział Nauk Ekonomicznych i Zarządzania"
address_line2 = "UMK w Toruniu"
address_line3 = "ul. Gagarina 13a, 87-100 Toruń"
phone = " Edycja Toruń  <br> +48 56 611 47 66 " # general phone 
phone2 = " Edycja 'Online' <br>  +48 56 611 46 27 "

####
## +48 56 611 47 66
## ninazwak@umk.pl
## +48 56 611 46 27
### barbara.polaszek@umk.pl


facebook = "https://www.facebook.com/projectmanagementUMK/"
linkedin = "https://www.linkedin.com/company/wneizumk"
#twitter = "https://twitter.com/"
#dribbble = "https://dribbble.com/"
#instagram = "https://www.instagram.com/"

map_url = "https://www.google.com/maps?q=Wydział+Nauk+Ekonomicznych+i+Zarządzania+UMK+w+Toruniu&output=embed"
map_pin_url = "https://maps.google.com/maps?q=Wydzia%C5%82+Nauk+Ekonomicznych+i+Zarz%C4%85dzania+UMK+w+Toruniu"
mapMarker = "images/marker.png"


##################################
# Site Menus  / Navabar settings #
##################################

[params.menu]
is_fixed = true
only_back_home = "Start"

# hugo menu reserved menu params 
[menu]

# Navbar Menus
[[menu.nav]]
name = "Strona Głowna"
url = "/"
weight = 1

[[menu.nav]]
name = "Program Studiów"
url = "#Program"
weight = 14


[[menu.nav]]
name = "Rekrutacja"
url = "#Rekrutacja"
weight = 17

[[menu.nav]]
name = "Partnerzy"
url = "#Partnerzy"
weight = 18

[[menu.nav]]
name = "Kontakt"
url = "#Kontakt"
weight = 30

[[menu.nav]]
name = "Zespół"
url = "#Zespol"
weight = 25


# Footer Quick links Menu
[[menu.quicklink]]
name = "Polityka prywatności"
url = "https://portal.umk.pl/pl/page/privacy"
weight = 1
[[menu.quicklink]]
name = "PODANIE - PM edycja ONLINE"
url = "https://www.umk.pl/kandydaci/podyplomowe/oferta/?id_kursu=4304"
weight = 2
[[menu.quicklink]]
name = "PODANIE - PM edycja Toruń"
url = "https://www.umk.pl/kandydaci/podyplomowe/oferta/?id_kursu=4303"
weight = 3

